import { StyleSheet } from 'react-native';
import { AppTheme } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: AppTheme.colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: AppTheme.spacing.md,
    paddingTop: AppTheme.spacing.md,
    paddingBottom: AppTheme.spacing.md,
    backgroundColor: AppTheme.colors.card,
    borderBottomWidth: 1,
    borderBottomColor: AppTheme.colors.border,
  },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: AppTheme.colors.cardInner,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeText: {
    fontSize: 18,
    color: AppTheme.colors.textDark,
  },
  title: {
    ...AppTheme.typography.sectionTitle,
    color: AppTheme.colors.textDark,
  },
  filterToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: AppTheme.spacing.md,
    backgroundColor: AppTheme.colors.card,
    borderBottomWidth: 1,
    borderBottomColor: AppTheme.colors.border,
  },
  filterToggleText: {
    ...AppTheme.typography.body,
    color: AppTheme.colors.primary,
    fontWeight: '600',
  },
  filterBadge: {
    marginLeft: AppTheme.spacing.sm,
    backgroundColor: AppTheme.colors.primary,
    borderRadius: 10,
    paddingHorizontal: AppTheme.spacing.sm,
    paddingVertical: 2,
  },
  filterBadgeText: {
    color: AppTheme.colors.card,
    ...AppTheme.typography.small,
    fontWeight: 'bold',
  },
  filtersContainer: {
    backgroundColor: AppTheme.colors.card,
    paddingHorizontal: AppTheme.spacing.md,
    paddingBottom: AppTheme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: AppTheme.colors.border,
  },
  filterRow: {
    marginTop: AppTheme.spacing.md,
  },
  filterLabel: {
    ...AppTheme.typography.body,
    fontWeight: '600',
    color: AppTheme.colors.textDark,
    marginBottom: AppTheme.spacing.sm,
  },
  filterChips: {
    flexDirection: 'row',
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: AppTheme.spacing.sm,
    backgroundColor: AppTheme.colors.cardInner,
    borderRadius: 20,
    marginRight: AppTheme.spacing.sm,
    borderWidth: 1,
    borderColor: AppTheme.colors.border,
  },
  chipActive: {
    backgroundColor: AppTheme.colors.primary,
    borderColor: AppTheme.colors.primary,
  },
  chipText: {
    ...AppTheme.typography.small,
    color: AppTheme.colors.textMuted,
    fontWeight: '500',
  },
  chipTextActive: {
    color: AppTheme.colors.card,
  },
  clearButton: {
    marginTop: AppTheme.spacing.md,
    paddingVertical: 10,
    backgroundColor: '#ff3b3020',
    borderRadius: AppTheme.borderRadius.sm,
    alignItems: 'center',
  },
  clearButtonText: {
    color: AppTheme.colors.danger,
    fontWeight: '600',
  },
  countContainer: {
    paddingHorizontal: AppTheme.spacing.md,
    paddingVertical: AppTheme.spacing.sm,
    backgroundColor: AppTheme.colors.background,
  },
  countText: {
    ...AppTheme.typography.small,
    color: AppTheme.colors.textMuted,
  },
  listContent: {
    paddingHorizontal: AppTheme.spacing.md,
    paddingBottom: 40,
  },
  transactionItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: AppTheme.colors.card,
    borderRadius: AppTheme.borderRadius.md,
    padding: AppTheme.spacing.md,
    marginTop: AppTheme.spacing.sm,
    ...AppTheme.shadows.card,
  },
  txLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  txIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  txIcon: {
    fontSize: 18,
  },
  txInfo: {
    marginLeft: AppTheme.spacing.md,
    flex: 1,
  },
  txType: {
    ...AppTheme.typography.body,
    fontWeight: 'bold',
    color: AppTheme.colors.textDark,
    textTransform: 'capitalize',
  },
  txSubtitle: {
    ...AppTheme.typography.small,
    fontWeight: '500',
    color: AppTheme.colors.textMuted,
    marginTop: 2,
  },
  txDate: {
    ...AppTheme.typography.small,
    color: AppTheme.colors.textMuted,
    marginTop: 2,
  },
  txWallet: {
    fontSize: 11,
    color: AppTheme.colors.textLight,
    marginTop: 2,
  },
  txRight: {
    alignItems: 'flex-end',
  },
  txTokenRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  tokenIcon: {
    width: 16,
    height: 16,
    borderRadius: 8,
    marginRight: AppTheme.spacing.xs,
  },
  txAmount: {
    ...AppTheme.typography.body,
    fontWeight: '600',
  },
  txValue: {
    ...AppTheme.typography.small,
    color: AppTheme.colors.textMuted,
    marginTop: 2,
  },
  txTypeLabel: {
    fontSize: 11,
    color: AppTheme.colors.textMuted,
    marginTop: 2,
  },
  copyButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: AppTheme.colors.primary,
    borderRadius: 6,
  },
  copyButtonText: {
    color: AppTheme.colors.card,
    fontWeight: '600',
  },
  detailActionButton: {
    flex: 1,
    paddingVertical: AppTheme.spacing.md,
    paddingHorizontal: AppTheme.spacing.md,
    borderRadius: AppTheme.borderRadius.sm,
    backgroundColor: AppTheme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
  },
  detailActionText: {
    color: AppTheme.colors.card,
    fontWeight: '600',
  },
  chainBadge: {
    marginTop: AppTheme.spacing.xs,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: AppTheme.borderRadius.xs,
  },
  chainText: {
    fontSize: 10,
    color: AppTheme.colors.card,
    fontWeight: '600',
    textTransform: 'capitalize',
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 60,
  },
  loadingText: {
    marginTop: AppTheme.spacing.md,
    ...AppTheme.typography.body,
    color: AppTheme.colors.textMuted,
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 60,
    paddingHorizontal: 40,
  },
  emptyIcon: {
    fontSize: 48,
    marginBottom: AppTheme.spacing.md,
  },
  emptyTitle: {
    ...AppTheme.typography.sectionTitle,
    color: AppTheme.colors.textDark,
    marginBottom: AppTheme.spacing.sm,
  },
  emptySubtitle: {
    ...AppTheme.typography.body,
    color: AppTheme.colors.textMuted,
    textAlign: 'center',
  },
  errorContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 60,
  },
  errorText: {
    ...AppTheme.typography.body,
    color: AppTheme.colors.danger,
    marginBottom: AppTheme.spacing.md,
  },
  retryButton: {
    paddingHorizontal: AppTheme.spacing.xl,
    paddingVertical: 10,
    backgroundColor: AppTheme.colors.primary,
    borderRadius: AppTheme.borderRadius.sm,
  },
  retryText: {
    color: AppTheme.colors.card,
    fontWeight: '600',
  },
  // New styles for details modal
  detailHeader: {
    alignItems: 'center',
    marginBottom: AppTheme.spacing.xl,
    paddingBottom: AppTheme.spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: AppTheme.colors.border,
  },
  detailIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: AppTheme.spacing.md,
  },
  detailIcon: {
    fontSize: 32,
  },
  detailType: {
    ...AppTheme.typography.subtitle,
    color: AppTheme.colors.textDark,
    marginBottom: AppTheme.spacing.xs,
  },
  detailDate: {
    ...AppTheme.typography.body,
    color: AppTheme.colors.textMuted,
    marginBottom: AppTheme.spacing.md,
  },
  statusBadge: {
    paddingHorizontal: AppTheme.spacing.md,
    paddingVertical: AppTheme.spacing.xs,
    borderRadius: AppTheme.borderRadius.md,
  },
  statusText: {
    ...AppTheme.typography.small,
    fontWeight: 'bold',
  },
  detailSection: {
    backgroundColor: AppTheme.colors.card,
    borderRadius: AppTheme.borderRadius.md,
    padding: AppTheme.spacing.md,
    marginBottom: AppTheme.spacing.md,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: AppTheme.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: AppTheme.colors.cardInner,
  },
  detailLabel: {
    ...AppTheme.typography.body,
    color: AppTheme.colors.textMuted,
    flex: 1,
  },
  detailValue: {
    ...AppTheme.typography.body,
    color: AppTheme.colors.textDark,
    fontWeight: '500',
    flex: 2,
    textAlign: 'right',
  },
  sectionTitle: {
    ...AppTheme.typography.body,
    fontWeight: 'bold',
    color: AppTheme.colors.textDark,
    marginBottom: AppTheme.spacing.md,
  },
  transferCard: {
    backgroundColor: AppTheme.colors.card,
    borderRadius: AppTheme.borderRadius.md,
    padding: AppTheme.spacing.md,
    marginBottom: AppTheme.spacing.md,
    borderWidth: 1,
    borderColor: AppTheme.colors.border,
  },
  transferHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: AppTheme.spacing.sm,
  },
  transferSymbol: {
    ...AppTheme.typography.body,
    fontWeight: 'bold',
    color: AppTheme.colors.textDark,
  },
  transferAmount: {
    ...AppTheme.typography.body,
    fontWeight: '600',
  },
  transferDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  transferDetailText: {
    ...AppTheme.typography.small,
    color: AppTheme.colors.textMuted,
  },
  emptyText: {
    textAlign: 'center',
    color: AppTheme.colors.textLight,
    fontStyle: 'italic',
    marginTop: AppTheme.spacing.md,
  },
  copyButtonSmall: {
    backgroundColor: AppTheme.colors.cardInner,
    paddingHorizontal: AppTheme.spacing.sm,
    paddingVertical: AppTheme.spacing.xs,
    borderRadius: AppTheme.borderRadius.xs,
  },
  copyButtonTextSmall: {
    fontSize: 10,
    color: AppTheme.colors.primary,
    fontWeight: '600',
  },
});
