import { StyleSheet } from 'react-native';
import { AppTheme } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: AppTheme.colors.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: AppTheme.spacing.lg,
    paddingTop: 60,
    backgroundColor: AppTheme.colors.card,
  },
  welcomeText: {
    ...AppTheme.typography.body,
    color: AppTheme.colors.textMuted,
  },
  usernameText: {
    ...AppTheme.typography.subtitle,
    color: AppTheme.colors.textDark,
  },
  summaryContainer: {
    backgroundColor: AppTheme.colors.card,
    margin: AppTheme.spacing.md,
    padding: AppTheme.spacing.lg,
    borderRadius: AppTheme.borderRadius.lg,
    ...AppTheme.shadows.card,
  },
  sectionTitle: {
    ...AppTheme.typography.sectionTitle,
    color: AppTheme.colors.textDark,
    marginBottom: AppTheme.spacing.md,
  },
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statCard: {
    flex: 1,
    alignItems: 'center',
    padding: AppTheme.spacing.md,
    backgroundColor: AppTheme.colors.cardInner,
    borderRadius: AppTheme.borderRadius.md,
    marginHorizontal: AppTheme.spacing.xs,
    marginBottom: AppTheme.spacing.sm,
  },
  statValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: AppTheme.colors.primary,
    marginBottom: AppTheme.spacing.xs,
  },
  statLabel: {
    ...AppTheme.typography.small,
    padding: AppTheme.spacing.xs,
    color: AppTheme.colors.textMuted,
    textAlign: 'center',
  },
  actionsContainer: {
    backgroundColor: AppTheme.colors.card,
    margin: AppTheme.spacing.md,
    marginTop: 0,
    padding: AppTheme.spacing.lg,
    borderRadius: AppTheme.borderRadius.lg,
    ...AppTheme.shadows.card,
  },
  chartContainer: {
    backgroundColor: AppTheme.colors.card,
    margin: AppTheme.spacing.md,
    marginTop: 0,
    borderRadius: AppTheme.borderRadius.lg,
    padding: AppTheme.spacing.lg,
    ...AppTheme.shadows.card,
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  actionButton: {
    flex: 1,
    backgroundColor: AppTheme.colors.primary,
    paddingVertical: AppTheme.spacing.md,
    borderRadius: AppTheme.borderRadius.sm,
    marginHorizontal: AppTheme.spacing.xs,
    alignItems: 'center',
  },
  actionButtonText: {
    color: AppTheme.colors.card,
    fontWeight: '600',
    ...AppTheme.typography.body,
  },
  exportButton: {
    flex: 1,
    backgroundColor: AppTheme.colors.card,
    borderWidth: 1,
    borderColor: AppTheme.colors.primary,
    paddingVertical: AppTheme.spacing.md,
    borderRadius: AppTheme.borderRadius.sm,
    marginHorizontal: AppTheme.spacing.xs,
    alignItems: 'center',
  },
  exportButtonText: {
    color: AppTheme.colors.primary,
    fontWeight: '600',
    ...AppTheme.typography.body,
  },
  portfolioContainer: {
    backgroundColor: AppTheme.colors.card,
    margin: AppTheme.spacing.md,
    marginTop: 0,
    borderRadius: AppTheme.borderRadius.lg,
    ...AppTheme.shadows.card,
    paddingTop: AppTheme.spacing.lg,
    paddingHorizontal: AppTheme.spacing.lg,
    marginBottom: 40,
  },
  emptyState: {
    alignItems: 'center',
    padding: 40,
  },
  emptyTitle: {
    ...AppTheme.typography.sectionTitle,
    color: AppTheme.colors.textDark,
    marginBottom: AppTheme.spacing.sm,
  },
  emptySubtitle: {
    ...AppTheme.typography.body,
    color: AppTheme.colors.textMuted,
    textAlign: 'center',
    marginBottom: AppTheme.spacing.lg,
  },
  addWalletButton: {
    backgroundColor: AppTheme.colors.success,
    paddingHorizontal: AppTheme.spacing.xl,
    paddingVertical: AppTheme.spacing.md,
    borderRadius: AppTheme.borderRadius.sm,
  },
  addWalletButtonText: {
    color: AppTheme.colors.card,
    fontWeight: '600',
    ...AppTheme.typography.body,
  },
  headerButtons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  shareButton: {
    marginRight: AppTheme.spacing.sm,
    backgroundColor: AppTheme.colors.primary,
    paddingHorizontal: 10,
    paddingVertical: AppTheme.spacing.sm,
    borderRadius: AppTheme.borderRadius.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shareButtonText: {
    color: AppTheme.colors.card,
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: AppTheme.spacing.lg,
  },
  shareCard: {
    width: 340,
    height: 500,
    borderRadius: AppTheme.borderRadius.xl,
    padding: 32,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 12,
    justifyContent: 'space-between',
    marginBottom: AppTheme.spacing.xl,
  },
  shareTitle: {
    ...AppTheme.typography.body,
    fontWeight: '700',
    color: AppTheme.colors.textDark,
    marginBottom: AppTheme.spacing.sm,
  },
  shareValue: {
    fontSize: 28,
    fontWeight: '800',
    color: AppTheme.colors.primary,
    marginBottom: 6,
  },
  shareChange: {
    ...AppTheme.typography.body,
    fontWeight: '700',
    marginBottom: AppTheme.spacing.md,
  },
  shareMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignSelf: 'stretch',
    paddingHorizontal: AppTheme.spacing.md,
    marginBottom: AppTheme.spacing.md,
  },
  shareMeta: {
    ...AppTheme.typography.small,
    color: AppTheme.colors.textMuted,
  },
  shareActions: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  shareActionButton: {
    flex: 1,
    marginHorizontal: AppTheme.spacing.sm,
    backgroundColor: AppTheme.colors.primary,
    paddingVertical: AppTheme.spacing.md,
    borderRadius: 10,
    alignItems: 'center',
  },
  shareActionText: {
    color: AppTheme.colors.card,
    fontWeight: '700',
  },
  closeButton: {
    backgroundColor: AppTheme.colors.border,
  },
  shareAttribution: {
    fontSize: 10,
    color: AppTheme.colors.textLight,
    marginTop: AppTheme.spacing.sm,
    fontStyle: 'italic',
  },
  // New gradient share card styles
  modalCloseButton: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 10,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 20,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCloseText: {
    color: AppTheme.colors.card,
    fontSize: 18,
    fontWeight: 'bold',
  },
  shareHeader: {
    alignItems: 'center',
    marginBottom: AppTheme.spacing.xl,
  },
  shareAppName: {
    fontSize: 24,
    fontWeight: '900',
    color: AppTheme.colors.card,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
    marginBottom: AppTheme.spacing.xs,
  },
  shareSubtitle: {
    ...AppTheme.typography.body,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.9)',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  shareContent: {
    alignItems: 'center',
    marginBottom: AppTheme.spacing.md,
    flex: 1,
    justifyContent: 'center',
  },
  shareTotalLabel: {
    ...AppTheme.typography.body,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.8)',
    marginBottom: AppTheme.spacing.sm,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  shareTotalValue: {
    fontSize: 36,
    fontWeight: '900',
    color: AppTheme.colors.card,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
    marginBottom: AppTheme.spacing.md,
  },
  shareChangeContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: AppTheme.spacing.sm,
  },
  shareChangeValue: {
    fontSize: 22,
    fontWeight: '800',
    color: AppTheme.colors.card,
    marginRight: AppTheme.spacing.sm,
    textShadowColor: 'rgba(0,0,0,0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  shareChangePercent: {
    ...AppTheme.typography.sectionTitle,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.9)',
    textShadowColor: 'rgba(0,0,0,0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  shareTimeLabel: {
    ...AppTheme.typography.small,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.7)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: AppTheme.spacing.md,
  },
  shareStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    paddingHorizontal: AppTheme.spacing.md,
    marginTop: 6,
  },
  shareStatItem: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: AppTheme.borderRadius.md,
    paddingHorizontal: AppTheme.spacing.md,
    paddingVertical: AppTheme.spacing.sm,
    minWidth: 72,
    marginHorizontal: 6,
  },
  shareStatValue: {
    fontSize: 20,
    fontWeight: '800',
    color: AppTheme.colors.card,
    marginBottom: 2,
  },
  shareStatLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.8)',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  shareFooter: {
    alignItems: 'center',
    marginTop: 'auto',
  },
  shareFooterText: {
    ...AppTheme.typography.small,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.8)',
    marginBottom: AppTheme.spacing.xs,
  },
  shareWatermark: {
    fontSize: 10,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.6)',
    textTransform: 'lowercase',
  },
  cancelActionButton: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  cancelActionText: {
    color: AppTheme.colors.card,
    fontWeight: '600',
  },
});
